#!/usr/bin/env python3
import sys
import os
import helpers
from termcolor import colored
from analyzer import Analyzer

def main():

    if len(sys.argv)!= 2:
        print("Usage: tweets.py @user")
        sys.exit(1)
       
       
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
        
        
    tweets = helpers.get_user_timeline(sys.argv[1], 50)
    
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored(tweet, "green"))
        elif score < 0.0:
            print(colored(tweet, "red"))
        else:
            print(colored(tweet, "yellow"))

if __name__ == "__main__":
    main()
    
